apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vlwh4ksnj-nodejs 
  janus-idp.io/tekton: vlwh4ksnj-nodejs
  backstage.io/kubernetes-id: vlwh4ksnj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vlwh4ksnj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml