apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vlwh4ksnj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vlwh4ksnj-nodejs 
  name: vlwh4ksnj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vlwh4ksnj-nodejs 
